extensions:
  dx_genstudio/translation/1:
    $include: src/ext.config.yaml
    runtimeManifest:
      packages:
        translation:
          license: Apache-2.0
          actions:
            getSupportedLocales:
              function: src/actions/getSupportedLocales.js
              web: 'yes'
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: true
                final: true
