name: GenStudio MLR Claims App Workflow

on:
  pull_request:
    paths:
      - "genstudio-mlr-claims-app/**"
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: '["genstudio-mlr-claims-app"]'
      environment: '["OrgStg_MLR_WsPrd"]' #"TEST",
    secrets: inherit
