name: Create Validation Main

on:
  push:
    branches:
      - main
    paths:
      - "genstudio-create-validation/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-create-validation
      environment: '["Genstudio Engineering 01 - genstudio-create-validation - workspace Production", "GenStudio GA PAT04 - genstudio-create-validation - workspace Production"]'
    secrets: inherit
