name: External Template App Main

on:
  push:
    branches:
      - main
    paths:
      - "genstudio-external-template-app/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-external-template-app
      environment: '["Genstudio Engineering 01 - genstudio-external-template-app - workspace Production", "GenStudio GA PAT04 - genstudio-external-template-app - workspace Production", "GenStudio Internal - E2E Tests - genstudio-external-template-app - workspace Production"]'
    secrets: inherit
