name: GenStudio Create Validation Workflow

on:
  pull_request:
    paths:
      - "genstudio-create-validation/**"
  workflow_dispatch:

jobs:
  pr:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-create-validation
      environment: '["Genstudio Engineering 01 - genstudio-create-validation - workspace Stage", "GenStudio GA PAT04 - genstudio-create-validation - workspace Stage", "GenStudio GA PAT04 - genstudio-create-validation - workspace Production"]'
    secrets: inherit
