name: MLR Claims

on:
  pull_request:
    paths:
      - "genstudio-mlr-claims-app/**"
  workflow_dispatch:

jobs:
  pr:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-mlr-claims-app
      environment: '["Genstudio Engineering 01 - genstudio-mlr-claims-app - workspace Stage", "GenStudio GA PAT04 - genstudio-mlr-claims-app - workspace Stage", "GenStudio Internal - E2E Tests - genstudio-mlr-claims-app - workspace Stage"]'
    secrets: inherit
