name: genstudio e2e app PR

on:
  pull_request:
    paths:
      - "genstudio-e2e-app/**"
  workflow_dispatch:

jobs:
  pr:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-e2e-app
      environment: |
        [
          "GenStudio Internal - E2E Tests - genstudio-e2e-app - workspace Stage",
          "GenStudio Internal - E2E Tests - genstudio-e2e-app - workspace Production"
        ]
    secrets: inherit
