name: IO Runtime App

on:
  pull_request:
    paths:
      - "genstudio-io-runtime-app/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-io-runtime-app
      environment: '["Genstudio Engineering 01 - genstudio-io-runtime-app - workspace Stage"]'
    secrets: inherit
