name: AIO App CI

on: [pull_request]
jobs:
  test:
    name: Test PR
    strategy:
      matrix:
        node-version: ["20"]
        os: [macOS-latest] # [macOS-latest, ubuntu-latest, windows-latest]
        app: [genstudio-mlr-claims-app]
        environment: [TEST] # [development, staging, production]
    runs-on: ${{ matrix.os }}
    environment: ${{ matrix.environment }}
    defaults:
      run:
        working-directory: ${{ matrix.app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Environment: ${{ matrix.environment }}"
          pwd
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('${{ matrix.app }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          version: 10.x.x
      - name: Auth
        uses: adobe/aio-apps-action@3.3.0
        with:
          command: oauth_sts
          CLIENTID: ${{ secrets.CLIENTID }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET }}
          TECHNICALACCOUNTID: ${{ secrets.TECHNICALACCOUNTID }}
          TECHNICALACCOUNTEMAIL: ${{ secrets.TECHNICALACCOUNTEMAIL }}
          IMSORGID: ${{ secrets.IMSORGID }}
          SCOPES: ${{ secrets.SCOPES }}
      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
        uses: adobe/aio-apps-action@3.3.0
        with:
          command: build
      # - name: Deploy
      #   env:
      #     AIO_RUNTIME_NAMESPACE: ${{ secrets.AIO_RUNTIME_NAMESPACE }}
      #     AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH }}
      #     AIO_PROJECT_ID: ${{ secrets.AIO_PROJECT_ID }}
      #     AIO_PROJECT_NAME: ${{ secrets.AIO_PROJECT_NAME }}
      #     AIO_PROJECT_ORG_ID: ${{ secrets.AIO_PROJECT_ORG_ID }}
      #     AIO_PROJECT_WORKSPACE_ID: ${{ secrets.AIO_PROJECT_WORKSPACE_ID }}
      #     AIO_PROJECT_WORKSPACE_NAME: ${{ secrets.AIO_PROJECT_WORKSPACE_NAME }}
      #     AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ secrets.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES }}
      #   uses: adobe/aio-apps-action@3.3.0
      #   with:
      #     os: ${{ matrix.os }}
      #     command: deploy
      #     noPublish: true
