name: GenStudio App Template PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  pr:
    uses: ./.github/workflows/aio-app-template.yml
    with:
      app: genstudio-app-template
      # See scripts folder for how to programmatically create the environment
      environment: '["You Github Environment Name 1", "You Github Environment Name 2"]'
    secrets: inherit
